// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ36WxVS_QFzmcgpgV451iv6Y8I1XMits',
    appId: '1:707381991855:android:f44128d486fe578e98b75a',
    messagingSenderId: '707381991855',
    projectId: 'medo-6917b',
    storageBucket: 'medo-6917b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfgFYaeUxmwbPmogQUqvreju-45IHNXXA',
    appId: '1:707381991855:ios:954d59f0c0bafaf498b75a',
    messagingSenderId: '707381991855',
    projectId: 'medo-6917b',
    storageBucket: 'medo-6917b.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD45EroiJhIEm7piX8BqTEkcdAu3fL5PsY',
    appId: '1:707381991855:web:bf484e0885897ce898b75a',
    messagingSenderId: '707381991855',
    projectId: 'medo-6917b',
    authDomain: 'medo-6917b.firebaseapp.com',
    storageBucket: 'medo-6917b.firebasestorage.app',
    measurementId: 'G-Q1MG2T6Z1H',
  );
}
